### ISSUE TITLE
[Tracking] Standable N-API

### ISSUE THREAD

**Issue by southorange0929** [ohos-rs/example#15]
## Not support by ohos-rs
- [ ] napi_queue_async_work_with_qos
- [ ] napi_load_module
- [ ] napi_create_object_with_properties
- [ ] napi_create_object_with_named_properties
- [ ] napi_coerce_to_native_binding_object

## Not support by harmoy
- [ ] napi_fatal_exception

**Comment by richerfu** [comment]
For napi_create_object_with_properties napi_create_object_with_named_properties napi_coerce_to_native_binding_object and sendable

PR is welcome
